### ISSUE TITLE
Remove old references to Crowdocracy and The DAP

### ISSUE THREAD

**Issue by dsernst** [liquidvote/org#6]
I think these things' time has come, and now they only distract and confuse from Liquid Democracy.

### TODO

- [x] update github org away from `crowdocracy`
- [ ] put a notice at the top of thedap.org about the switch
- [x] update Gitter org names (`crowdocracy`)
- [x] update Gitter room name (`thedap`)

**Comment by dsernst** [comment]
- [ ] update github org away from `crowdocracy`
- [ ] stop linking to thedap.org, or at least put a notice at the top of that site about the switch
- [ ] update Gitter chatroom names

**Comment by dsernst** [comment]
@jaredscheib brought up (earlier tonight in person) that it would be good to update the gitter chatroom name

**Comment by dsernst** [comment]
I sent in a support request to Gitter

**Comment by dsernst** [comment]
Gitter has moved the org from `crowdocracy` to `liquidvote`, and the old link redirects 👍 . Still need to get the individual room renamed away from `thedap`
